title:              LEGO CODING
email:              dntjd851@naver.com
description:        Wooseong's Blog with the intention of assembling like Lego!
author:             Yoon Wooseong
baseurl:            "/yoonwooseong.github.io"
url:                "https://yoonwooseong.github.io"

# Social Profiles
twitter_username:   null
github_username:    yoonwooseong
facebook_username:  null
instagram_username:  95wooseong
linkedin_username:  null

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
